function Hd = untitled
%UNTITLED Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 03-Oct-2017 21:57:19
%

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 30000;  % Sampling Frequency

Fpass1 = 2600;        % First Passband Frequency
Fstop1 = 2800;        % First Stopband Frequency
Fstop2 = 3200;        % Second Stopband Frequency
Fpass2 = 3300;        % Second Passband Frequency
Apass1 = 1;           % First Passband Ripple (dB)
Astop  = 45;          % Stopband Attenuation (dB)
Apass2 = 1;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);


for i=1:399
      
      h_hex = fi(Hd(i),1,16,15);  % Convierte los coeficientes en S16.15
      s = ['0x' h_hex.hex];   %Crea una cadena y antepone 0x
      disp(s)  % Muestra la cadena por consola
end

% [EOF]
